services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: safetravel-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - Loki__Url=http://loki:3100
      - HangfireDashboard__Username=admin
      - HangfireDashboard__Password=hangfire@123
    depends_on:
      - redis
      - loki
    restart: unless-stopped

  redis:
    image: redis:8.4-alpine
    container_name: safetravel-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  loki:
    image: grafana/loki:3.6.4
    container_name: safetravel-loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.3.2
    container_name: safetravel-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
    restart: unless-stopped
